include("platform:common-meta")
include("platform:common-core")
include("platform:server-core")
include("platform:server-postgres")
include("platform:server-atomikos")
include("platform:server-file-storage")
include("platform:web-core")
include("platform:gradle")
include("demo:server")
include("demo:site")
include("demo:gradle")
rootProject.name ="elsa"
